name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.1
  flutter_secure_storage: ^9.0.0
  flutter_dotenv: ^5.1.0
  provider: ^6.1.1
  geolocator: ^14.0.1
  google_maps_flutter: ^2.12.2
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
